public enum CraftCategoryId // TypeDefIndex: 7096
{
    EMPTY = 0,
    Cook_Handmade = 1,
    Cook_Frypan = 2,
    Cook_Pan = 3,
    Cook_Steamer = 4,
    Cook_Knife = 5,
    Cook_Mixer = 6,
    Cook_Oven = 7,
    Drug = 8,
    Weapon_Sword = 9,
    Weapon_DHSword = 10,
    Weapon_Spear = 11,
    Weapon_Ax = 12,
    Weapon_Hammer = 13,
    Weapon_TwinSword = 14,
    Weapon_Fist = 15,
    Weapon_Wand = 16,
    FarmTool = 17,
    Shield = 18,
    Accessory = 19,
    Hat = 20,
    Shoes = 21,
    Armor = 22,
    Max = 23,
}